branch-defaults:
  master:
    environment: Django-Null-project-dev
    group_suffix: null
global:
  application_name: Django_Null_project
  branch: null
  default_ec2_keyname: shh
  default_platform: Python 3.4
  default_region: ap-northeast-2
  profile: eb-cli
  repository: null
  sc: git
